"""add_phase7_ai_insights

Revision ID: 0539e3c8670c
Revises: b7bda0dbe198
Create Date: 2026-06-17 10:51:30.950080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.models

# revision identifiers, used by Alembic.
revision: str = '0539e3c8670c'
down_revision: Union[str, Sequence[str], None] = 'b7bda0dbe198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_pg = bind.dialect.name == 'postgresql'
    default_val = '{}' if is_pg else '[]'
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_theme', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('theme_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('why_matters', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('short_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medium_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_lesson', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lessons_learned', postgresql.ARRAY(sa.String()).with_variant(app.db.models.SQLiteArray(), 'sqlite'), nullable=False, server_default=default_val))
        batch_op.add_column(sa.Column('emotion_initial', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emotion_catalyst', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emotion_outcome', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('emotion_outcome')
        batch_op.drop_column('emotion_catalyst')
        batch_op.drop_column('emotion_initial')
        batch_op.drop_column('lessons_learned')
        batch_op.drop_column('key_lesson')
        batch_op.drop_column('medium_summary')
        batch_op.drop_column('short_summary')
        batch_op.drop_column('why_matters')
        batch_op.drop_column('theme_confidence')
        batch_op.drop_column('main_theme')

    # ### end Alembic commands ###
