"""add_phase6_ai_fields

Revision ID: b7bda0dbe198
Revises: bdf754fa6dad
Create Date: 2026-06-17 10:32:23.426585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.models

# revision identifiers, used by Alembic.
revision: str = 'b7bda0dbe198'
down_revision: Union[str, Sequence[str], None] = 'bdf754fa6dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_pg = bind.dialect.name == 'postgresql'
    default_val = '{}' if is_pg else '[]'
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_emotion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('secondary_emotions', postgresql.ARRAY(sa.String()).with_variant(app.db.models.SQLiteArray(), 'sqlite'), nullable=False, server_default=default_val))
        batch_op.add_column(sa.Column('emotion_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('embedding_reference_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('embedding_reference_id')
        batch_op.drop_column('emotion_confidence')
        batch_op.drop_column('secondary_emotions')
        batch_op.drop_column('primary_emotion')

    # ### end Alembic commands ###
